# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.version)

<module 'numpy.version' from '/opt/anaconda3/lib/python3.9/site-packages/numpy/version.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))
print(a)

[[[0.61408864 0.86937228 0.56614995 0.21842907 0.79154651]
  [0.89158056 0.1797661  0.37146942 0.55763867 0.70923605]
  [0.61984573 0.91726732 0.23330714 0.03224908 0.76605766]]

 [[0.84818086 0.00241795 0.55702543 0.78190368 0.17947732]
  [0.53414837 0.25087729 0.0621469  0.48184031 0.60687329]
  [0.20961441 0.1045267  0.49191315 0.78920037 0.2182889 ]]]


In [4]:
ab = np.random.default_rng()
a = ab.random((2, 3, 5))
a

array([[[0.26540367, 0.34436818, 0.16262488, 0.46221046, 0.8275459 ],
        [0.34623439, 0.74221869, 0.83572082, 0.59228075, 0.520852  ],
        [0.57711723, 0.73415228, 0.05097783, 0.17406118, 0.1958886 ]],

       [[0.78917381, 0.55440984, 0.63476761, 0.63526727, 0.37256239],
        [0.89887091, 0.74229111, 0.50838178, 0.75213062, 0.86599198],
        [0.24985374, 0.86721931, 0.76615214, 0.49919803, 0.51479592]]])

In [5]:
b = np.arange(9).reshape(2, 3, 5)
np.random.shuffle(b)
b

ValueError: cannot reshape array of size 9 into shape (2,3,5)

#### 4. Print *a*.


In [6]:
a = np.random.random((2,3,5))
print(a)

[[[0.10292737 0.50667598 0.95636483 0.24703319 0.24593356]
  [0.85024333 0.75590946 0.88687409 0.00212735 0.37796761]
  [0.93704952 0.821205   0.36187285 0.61018208 0.88928609]]

 [[0.78274697 0.49980543 0.46713574 0.65658331 0.23216779]
  [0.30607628 0.35330948 0.89600068 0.85531267 0.75306168]
  [0.82295228 0.54261786 0.94744549 0.41652255 0.52849999]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [24]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [28]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
print(a.size)
print(b.size)

#They do have the same size

30
30


In [29]:
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [33]:
np.add(a,b)

"""
I couldn't add them because they do not have the same shape.
"""

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [31]:
c = b.reshape((2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [32]:
np.add(a,c)

array([[[1.10292737, 1.50667598, 1.95636483, 1.24703319, 1.24593356],
        [1.85024333, 1.75590946, 1.88687409, 1.00212735, 1.37796761],
        [1.93704952, 1.821205  , 1.36187285, 1.61018208, 1.88928609]],

       [[1.78274697, 1.49980543, 1.46713574, 1.65658331, 1.23216779],
        [1.30607628, 1.35330948, 1.89600068, 1.85531267, 1.75306168],
        [1.82295228, 1.54261786, 1.94744549, 1.41652255, 1.52849999]]])

In [37]:
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [35]:
print (a)

[[[0.10292737 0.50667598 0.95636483 0.24703319 0.24593356]
  [0.85024333 0.75590946 0.88687409 0.00212735 0.37796761]
  [0.93704952 0.821205   0.36187285 0.61018208 0.88928609]]

 [[0.78274697 0.49980543 0.46713574 0.65658331 0.23216779]
  [0.30607628 0.35330948 0.89600068 0.85531267 0.75306168]
  [0.82295228 0.54261786 0.94744549 0.41652255 0.52849999]]]


In [38]:
print (d)

[[[1.10292737 1.50667598 1.95636483 1.24703319 1.24593356]
  [1.85024333 1.75590946 1.88687409 1.00212735 1.37796761]
  [1.93704952 1.821205   1.36187285 1.61018208 1.88928609]]

 [[1.78274697 1.49980543 1.46713574 1.65658331 1.23216779]
  [1.30607628 1.35330948 1.89600068 1.85531267 1.75306168]
  [1.82295228 1.54261786 1.94744549 1.41652255 1.52849999]]]


In [ ]:
"""
Every value in a has been added to every value in c.
"""

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [64]:
e = np.multiply(a,c) 

In [65]:
print(e)

[[[1.05940442e-02 2.56720552e-01 9.14633680e-01 6.10253960e-02
   6.04833168e-02]
  [7.22913727e-01 5.71399105e-01 7.86545643e-01 4.52562167e-06
   1.42859516e-01]
  [8.78061798e-01 6.74377655e-01 1.30951962e-01 3.72322169e-01
   7.90829748e-01]]

 [[6.12692815e-01 2.49805473e-01 2.18215804e-01 4.31101640e-01
   5.39018828e-02]
  [9.36826871e-02 1.24827590e-01 8.02817211e-01 7.31559766e-01
   5.67101887e-01]
  [6.77250460e-01 2.94434137e-01 8.97652948e-01 1.73491036e-01
   2.79312240e-01]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
"""
Yes, because every value of a has been multiplied by 1.
"""

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [66]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [67]:
f=np.empty([2,3,5])
print(f)

[[[1.05940442e-02 2.56720552e-01 9.14633680e-01 6.10253960e-02
   6.04833168e-02]
  [7.22913727e-01 5.71399105e-01 7.86545643e-01 4.52562167e-06
   1.42859516e-01]
  [8.78061798e-01 6.74377655e-01 1.30951962e-01 3.72322169e-01
   7.90829748e-01]]

 [[6.12692815e-01 2.49805473e-01 2.18215804e-01 4.31101640e-01
   5.39018828e-02]
  [9.36826871e-02 1.24827590e-01 8.02817211e-01 7.31559766e-01
   5.67101887e-01]
  [6.77250460e-01 2.94434137e-01 8.97652948e-01 1.73491036e-01
   2.79312240e-01]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [68]:
f = np.array((d))
f

array([[[0.10292737, 0.50667598, 0.95636483, 0.24703319, 0.24593356],
        [0.85024333, 0.75590946, 0.88687409, 0.00212735, 0.37796761],
        [0.93704952, 0.821205  , 0.36187285, 0.61018208, 0.88928609]],

       [[0.78274697, 0.49980543, 0.46713574, 0.65658331, 0.23216779],
        [0.30607628, 0.35330948, 0.89600068, 0.85531267, 0.75306168],
        [0.82295228, 0.54261786, 0.94744549, 0.41652255, 0.52849999]]])

In [69]:
a=np.where((f>d_min)&(f<d_mean),25,f)
b=np.where((f>d_mean)&(f<d_max),75,a)
c=np.where((f==d_mean),50,b)
d=np.where((f==d_min),0,c)
e=np.where((f==d_max),100,d)
print(e)

[[[ 25.  25. 100.  25.  25.]
  [ 75.  75.  75.   0.  25.]
  [ 75.  75.  25.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  25.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [70]:
print(d)

[[[25.         25.          0.95636483 25.         25.        ]
  [75.         75.         75.          0.         25.        ]
  [75.         75.         25.         75.         75.        ]]

 [[75.         25.         25.         75.         25.        ]
  [25.         25.         75.         75.         75.        ]
  [75.         25.         75.         25.         25.        ]]]


In [71]:
print(f)

[[[0.10292737 0.50667598 0.95636483 0.24703319 0.24593356]
  [0.85024333 0.75590946 0.88687409 0.00212735 0.37796761]
  [0.93704952 0.821205   0.36187285 0.61018208 0.88928609]]

 [[0.78274697 0.49980543 0.46713574 0.65658331 0.23216779]
  [0.30607628 0.35330948 0.89600068 0.85531267 0.75306168]
  [0.82295228 0.54261786 0.94744549 0.41652255 0.52849999]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [72]:
i=np.where((d>d_min)&(d<d_mean),"A",d)
j=np.where((d>d_mean)&(d<d_max),"B",i)
k=np.where((d==d_mean),"C",j)
l=np.where((d==d_min),"D",k)
m=np.where((d==d_max),"E",l)
print(m)

[[['25.0' '25.0' 'E' '25.0' '25.0']
  ['75.0' '75.0' '75.0' '0.0' '25.0']
  ['75.0' '75.0' '25.0' '75.0' '75.0']]

 [['75.0' '25.0' '25.0' '75.0' '25.0']
  ['25.0' '25.0' '75.0' '75.0' '75.0']
  ['75.0' '25.0' '75.0' '25.0' '25.0']]]
